name: minios Tester

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            qemu-system-i386 \
            xvfb \
            imagemagick \
            x11-apps

      - name: Start virtual display
        run: |
          Xvfb :99 -screen 0 1280x720x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run minios
        run: |
          export DISPLAY=:99

          timeout 30 make run

      - name: Capture screenshot
        run: |
          export DISPLAY=:99

          xwd -root -display :99 \
            | convert xwd:- screenshot.png

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: minios-screenshot
          path: screenshot.png
